language: r
sudo: false
cache: packages
r_github_packages:
- cloudyr/travisci
r_packages:
- covr
- drat
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  drat.sh
- Rscript -e "covr::codecov()"
- Rscript -e "travisci::restart_last_build('leeper/MTurkRGUI')"
env:
  global:
  - secure: Lgb6SLbbSWBaHiBHsdrRbq3MgvMbu/5Iv1VCjDqLu4vw9wzBmFHryYy6kBCHwTWjopYu7h8lDrb2U45SZxWgHX9cL0ubn3z6HW5UzWIRcpRDQ1H5oEeKzlCrEiG9CxsELXame2yq5+46GLpLrUZyEA4aLXvXlhKx9ds2uxxpAlA=
  - secure: h6fCtCVNtRRBs+dFspYg//M6q/bQT/8No/TkuXutqmJk0R84Zhuf/FGfCr8lrLFVqUmAWQqyEcJJcoC5lmIY1R0+WI8p7gSkM7Gkj8YwtLHH77s6h1nKcyxmAs/EBQw71El5NdPmWxXIDcGvfDytk5ms5AaRzXhIJAz82Bm9RWc=
  - secure: Lryi4zAqD+hB7hyaWsSx4SUlXOrRXDtteELBkREyku1FSEDPPendGg7Z0Sdaiy22nKEsfL4MUgIrVh1VqAtvqznyWGTc2NDGZArOVFhMS5ErA9MG6kN1g2jQCezuZN9VzKIIiftawjM+VKMIfyqdf4PAvVL4KdH6p+6p1Hr3wpA=
  - secure: P1gEvaxOf8M6ZpKQ0tGHT38c6nDUftOYOuTlm9wWp+RBozBHDWv2mk0Bmb2HkWd4Jc2MHhN/eCa4hPHTs6cdskvoLKAkP9QjNHY/QhIKpqtcL1HSs/MIry93D1itMYh4To9nWGNd5nDkqCRKax56FoOpXobDZ/0c76CMYpZDyc8=
